site_name: pdfmd
pages:
  - Home: 'index.md'
  - Concept: 'concept.md'
  - Commands:
    - clean: 'commands/clean.md'
    - config: 'commands/config.md'
    - edit: 'commands/edit.md'
    - init: 'commands/init.md'
    - rename: 'commands/rename.md'
    - show: 'commands/show.md'
    - sort: 'commands/sort.md'
    - stat: 'commands/stat.md'
  - Tags:
    - author: 'tags/author.md'
    - createdate: 'tags/createdate.md'
    - keywords: 'tags/keywords.md'
    - subject: 'tags/subject.md'
    - title: 'tags/title.md'
  - Hiera: 'hiera.md'
  - About: 'about.md'

